### ISSUE TITLE
Better design for individual hunt unit in sidebar

### ISSUE THREAD

**Issue by rhewitt22** [USFWS/hunting-opportunities#2]
1. We could use icons rather than bullets to signify the type of regulation.
2. Is the centered text helping here?
3. 

![Hunt unit display](https://user-images.githubusercontent.com/3673374/71263221-7c976680-230f-11ea-95fc-a416f0dd0966.jpg)

**Comment by kgilbert-design** [comment]
I think we should left justify everything, esp since we have the blue color and font different already. 

Also, I like the idea if icons.  Not sure what to chose for 
method of take- bow and arrow
bag limit? not sure what to do here. 
date/time -clock, and a bag for bag limit?

All icons would be a grey color as described in the overall style sheet.
