### ISSUE TITLE
Zoom to hunt unit from individual refuge info in sidebar

### ISSUE THREAD

**Issue by rhewitt22** [USFWS/hunting-opportunities#6]
When you click on a blue (or orange) dot representing an individual refuge where hunting opportunities exist you should be able to zoom to each individual hunt unit open on the refuge from the sidebar.

![Screen Shot 2019-12-20 at 10 09 10 AM](https://user-images.githubusercontent.com/3673374/71263932-f845e300-2310-11ea-8dde-def08384aa53.jpg)

**Comment by rhewitt22** [comment]
There's a zoom button next to each hunt unit that will fly the map to the unit in question (74e282133d6dfbfedceef5f968adff7e77ca74c5)

![Screen Shot 2019-12-20 at 1 24 53 PM](https://user-images.githubusercontent.com/3673374/71281531-24bb2880-232c-11ea-9b37-ec60fd9d5d87.jpg)

**Comment by kgilbert-design** [comment]
- Can we retitle this view "Refuge Hunt Areas"

-  CLASSIC BLUE for the the title and BLACK for body copy

- Swap out the symbol below to mean zoom instead of the word zoom. 

-  Text Size and spacing doesn't need to change from what you have now. 

![HuntArea by RefugeList-03-03](https://user-images.githubusercontent.com/59093595/71295477-f8160980-2349-11ea-86e1-db86b1f28267.png)
